general:
  max_attempts: 3
  console_output: True
offline:
  offline_mode_enabled: False
  card_json: 'oracle-cards-20260217100533.json' 
api_options:
  random_card_uri: 'https://api.scryfall.com/cards/random'
  set_exclusion: '-set:'
  manavalue_filter: 'mv='
  creature_filter: 't=creature'
  request_timeout_in_s: 30
  max_number_faces: 2
  splitcard_layouts:
    - 'split'
    - 'flip'
    - 'transform'
    - 'modal_dfc'
  layout_edgecases:
    - 'meld'
  sets_to_exclude:
    - 'UGL'
    - 'UNH'
    - 'UST'
    - 'UND'
    - 'UNF'
debug:
  debug_mode_enabled: False
  test_query_options: 'layout=modal_dfc' #'name=Hostile%20Hostel'
image_options:
  default_img_mode: True
  img_width: 48
  img_height: 24
printer:
  backend: 'usb' #win32raw, usb
  win_printer_name: 'POS-58'
  vid: 0x0416
  pid: 0x5011
  codepage: "OEM437"
  print_image: False
  print_text: False
  print_oracle_qr: False
  max_img_width_in_px: 384
  img_print_implementation: 'bitImageRaster'

